export enum PropertyTypeEnum {
  HOUSE = 'House',
  APARTMENT = 'Apartment',
  BARN = 'Barn',
  BEDANDBREAKFAST = 'Bed and Breakfast',
  BOAT = 'Boat',
  CABIN = 'Cabin',
  CAMPER = 'Camper',
  CASAPARTICULAR = 'Casaparticular',
  CASTLE = 'Castle',
  CAVE = 'Cave',
  CONTAINER = 'Container',
  DOME = 'Dome',
  HOTEL = 'Hotel',
  FARM = 'Farm',
  HOUSEBOAT = 'Houseboat',
  KEZHAN = 'Kezhan',
  TENT = 'Tent',
  TINYHOME = 'Tinyhome',
  TOWER = 'Tower',
  TREEHOUSE = 'Treehouse',
  YURT = 'Yurt',
  WINDMILL = 'Windmill',
}
